services:
  flask_app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      FLASK_APP: main.py
      FLASK_ENV: development
      FLASK_DEBUG: 1
      FLASK_PORT: 5000
      REDIS_LOCATION: redis
    ports:
      - '5000:5000'

  redis:
    image: redis:7.0
    command: redis-server --appendonly yes
    ports:
      - '6379:6379'
